### ISSUE TITLE
Date mask glitch when deleting a value from date inputs is forbidden

### ISSUE THREAD

**Issue by fbeceic** [croz-ltd/tiller#118]
## Basic information

* Tiller version: 1.6.1
* Module: date

## Bug description

Date mask sometimes behaves strange when clicking away from any date input components.

When writing some specific dates, the value in the field changes to a non-date value.

List of components: `DateInput`, `DateRangeInput`, `DateTimeInput`

<img width="265" alt="image" src="https://github.com/croz-ltd/tiller/assets/44879477/f02c5acb-0efa-4466-9626-7ece5e3ceb6f">

### Expected behavior

Normal and consistent mask behaviour.

### Actual behavior

Mask shifts if the component is used in the described use case.

**Comment by jtomic-croz** [comment]
@fbeceic please add a screenshot of the field when the mask starts working wrong.
