### ISSUE TITLE
Greater control over Tab

### ISSUE THREAD

**Issue by mkatanec-croz** [croz-ltd/tiller#119]
## Basic information

* Tiller version: 1.6.1
* Module: core

## Enhancement description

Enable greater control over Tabs. Reach Tabs has prop `index` for setting index of currently selected tab. This will enable user to control Tabs component from outside of it.

### Current behaviour

For tabs control Tabs component only has `defaultIndex` prop

### Wanted behaviour

Tabs component has two additional props that are not required, `index` and `onTabChange` that will be passed to Reach Tabs component. There can even be a Hook `useTabs` that will return `currentIndex`, function for changing index and a hook that can be passed to Tabs component. `hook` would contain `index` and `onTabChange` which means that `useTabs` hook would also handle manual tab index management

**Comment by jtomic-croz** [comment]
@mkatanec-croz Valid issue. Currently, alternative is using something like `<Tabs defaultIndex={currentIndex} key={currentIndex}>`.
