### ISSUE TITLE
Improve active state of Sidebar/Top Navigation components' items

### ISSUE THREAD

**Issue by fbeceic** [croz-ltd/tiller#131]
## Basic information

* Tiller version: 1.7.0
* Module: menu

## Enhancement description

Improve consistency between `SidebarNavigation` and `TopNavigation` in active item detection.
Enable greater control over `SidebarNavigation.Item` and `TopNavigation.Item` subcomponents by providing a prop that will define whether or not a user is currently on the page defined by this item's `to` prop.

### Current behaviour

`TopNavigation` and `SidebarNavigation` components have fixed logic of determining when a user is on a given page, based on the `to` prop.

Also, `SidebarNavigation` and `TopNavigation` components are inconsistent:
 - `SidebarNavigation` strictly checks whether the pathname is equal to `to` prop
 - `TopNavigation` checks whether the pathname starts with `to` prop

For example, when using `SidebarNavigation` and I'm on a `/processes` page an item with the prop `to="/processes"` will be highlighted as active.
But, if i go to  `/processes/1` to look at process details the same item will not be active now, although it should be.

### Wanted behaviour

Active state of an item is determined either by existing logic (which should be made consistent between navigation components) or by logic defined using an optional `isActive` prop on `SidebarNavigation.Item` and `TopNavigation.Item` subcomponents.

**Comment by jtomic-croz** [comment]
@fbeceic Let's start with fixing the misalignment and switch both of the Navigations to `startsWith` logic and release it as a patch.

Afterwards, we can add `isActive` for some minor or major update
