### ISSUE TITLE
Storybook documentation example not working correctly - DataTable With Default Ascending Sort By Name

### ISSUE THREAD

**Issue by frankopapic** [croz-ltd/tiller#148]
## Basic information

* Tiller version:
  
* Module: DataTable
  
* Link to the complete executable reproducer if available (e.g. GitHub Repo): https://croz-ltd.github.io/tiller/iframe.html?viewMode=docs&id=component-library-data-display-datatable--with-default-ascending-sort-by-name&args=#with-default-ascending-sort-by-name

## Bug description

Not enough information about the sorting functionality of the DataTable component. The example used in the documentation is not working.

**Comment by jtomic-croz** [comment]
I'll mark this as documentation as it's not really a bug
