### ISSUE TITLE
DataTable sorting - hook proposal

### ISSUE THREAD

**Issue by fbeceic** [croz-ltd/tiller#149]
## Basic information

* Tiller version: 1.7.2
* Module: data-display

## Enhancement description

Sorting in the `DataTable` component could be made easier by providing an appropriate hook to ease the process, rather than relying on tracking state changing via the hook attached to the component.

The hook (e.g. `useSortableDataTable`) could accept data and column mappings and return a sorted data set to pass onto the component.

### Current behaviour

Sorting in the `DataTable` can only be implemented by tracking the state and writing a custom sorting logic.

### Wanted behaviour

`DataTable` sorting made possible by providing a default sorting hook to ease and reduce development process.

**Comment by jtomic-croz** [comment]
@fbeceic is this only for frontend sorting ? in cases where all the results are fetched to frontend and then sorted there?
