### ISSUE TITLE
Select Field, Date Input Field - keypress "Tab" focuses a random item on a screen

### ISSUE THREAD

**Issue by AnamariR** [croz-ltd/tiller#181]
## Basic information

* Tiller version: 1.7.4.
  
* Module:

Formik-elements  / Select Field (https://croz-ltd.github.io/tiller/?path=/docs/component-library-formik-elements-selectfield--select-field-factory)
Formik-elements / DateInputField (https://croz-ltd.github.io/tiller/?path=/docs/component-library-formik-elements-dateinputfield--with-label)

## Bug description

After choosing an option from the select field or a date from a date field and after they both close, after keyboard "tab" press, the focus goes on a random item at the beginning of the screen. 

### Steps to reproduce

Step 1: Open select field // Date Input Field 
Step 2: Pick an item // Select a date 
Step 3: System closes the Select Field // System closes date select
Step 4: Press "Tab" on keyboard

### Expected behavior

On keyboard "Tab press" system should focus the first next item. 

### Actual behavior

On keyboard "Tab press" system focuses an item at the beginning of the screen.

**Comment by fbeceic** [comment]
The forthcoming update will address the current issue, and there are ongoing plans to enhance form accessibility. This includes optimizing the fluidity and consistency of navigating between form elements using the tab key. 

The issue will remain open, serving as a focal point for incorporating these improvements in future updates.
