### ISSUE TITLE
DataTable - Preserving sort arrow on default sort

### ISSUE THREAD

**Issue by mnovaciccroz** [croz-ltd/tiller#236]
## Basic information

- Tiller version: 1.7.3
- Module: -
- Link to the complete executable reproducer if available (e.g. GitHub Repo): -

## Additional information

- none

## Enhancement description

- Keep the sort arrow displayed when the default sort is selected and the defaultSortBy prop is set.
 
### Current behaviour

- The arrow indicating the initial sort is cleared after no other sort is set.

### Wanted behaviour

- Always display the arrow indicating the initial sort when it's not sorted by any other column.

### Possible workarounds

- none

**Comment by jtomic-croz** [comment]
@mnovaciccroz pls update description in english

**Comment by LukaFilipovic99** [comment]
@mnovaciccroz I'm not sure if I understand your issue. As I know defaultSortBy prop is used only for declaring how DataTable should be sorted in it's initial state and in that case arrow will be displayed. After, you can sort table in another direction by clicking on column or even disable sorting. And if sorting is disabled, arrow will not be displayed which is wanted behaviour.
